//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.MiniProject208
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBMiniProject208Entities : DbContext
    {
        public DBMiniProject208Entities()
            : base("name=DBMiniProject208Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<x_addrbook> x_addrbook { get; set; }
        public virtual DbSet<x_address> x_address { get; set; }
        public virtual DbSet<x_biodata> x_biodata { get; set; }
        public virtual DbSet<x_catatan> x_catatan { get; set; }
        public virtual DbSet<x_certification_type> x_certification_type { get; set; }
        public virtual DbSet<x_client> x_client { get; set; }
        public virtual DbSet<x_education_level> x_education_level { get; set; }
        public virtual DbSet<x_employee> x_employee { get; set; }
        public virtual DbSet<x_employee_leave> x_employee_leave { get; set; }
        public virtual DbSet<x_employee_training> x_employee_training { get; set; }
        public virtual DbSet<x_identity_type> x_identity_type { get; set; }
        public virtual DbSet<x_keahlian> x_keahlian { get; set; }
        public virtual DbSet<x_leave_name> x_leave_name { get; set; }
        public virtual DbSet<x_leave_request> x_leave_request { get; set; }
        public virtual DbSet<x_marital_status> x_marital_status { get; set; }
        public virtual DbSet<x_menu_access> x_menu_access { get; set; }
        public virtual DbSet<x_menutree> x_menutree { get; set; }
        public virtual DbSet<x_note_type> x_note_type { get; set; }
        public virtual DbSet<x_organisasi> x_organisasi { get; set; }
        public virtual DbSet<x_placement> x_placement { get; set; }
        public virtual DbSet<x_religion> x_religion { get; set; }
        public virtual DbSet<x_rencana_jadwal> x_rencana_jadwal { get; set; }
        public virtual DbSet<x_rencana_jadwal_detail> x_rencana_jadwal_detail { get; set; }
        public virtual DbSet<x_riwayat_pekerjaan> x_riwayat_pekerjaan { get; set; }
        public virtual DbSet<x_riwayat_pelatihan> x_riwayat_pelatihan { get; set; }
        public virtual DbSet<x_riwayat_pendidikan> x_riwayat_pendidikan { get; set; }
        public virtual DbSet<x_role> x_role { get; set; }
        public virtual DbSet<x_schedule_type> x_schedule_type { get; set; }
        public virtual DbSet<x_sertifikasi> x_sertifikasi { get; set; }
        public virtual DbSet<x_skill_level> x_skill_level { get; set; }
        public virtual DbSet<x_sumber_loker> x_sumber_loker { get; set; }
        public virtual DbSet<x_time_period> x_time_period { get; set; }
        public virtual DbSet<x_timesheet> x_timesheet { get; set; }
        public virtual DbSet<x_timesheet_assessment> x_timesheet_assessment { get; set; }
        public virtual DbSet<x_training> x_training { get; set; }
        public virtual DbSet<x_training_organizer> x_training_organizer { get; set; }
        public virtual DbSet<x_training_type> x_training_type { get; set; }
        public virtual DbSet<x_undangan> x_undangan { get; set; }
        public virtual DbSet<x_undangan_detail> x_undangan_detail { get; set; }
        public virtual DbSet<x_userrole> x_userrole { get; set; }
    }
}
