//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.MiniProject208
{
    using System;
    using System.Collections.Generic;
    
    public partial class x_note_type
    {
        public long id { get; set; }
        public long created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public Nullable<long> modify_by { get; set; }
        public Nullable<System.DateTime> modify_on { get; set; }
        public Nullable<long> delete_by { get; set; }
        public Nullable<System.DateTime> delete_on { get; set; }
        public bool is_delete { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}
